apiVersion: v2
name: magda-auth-aaf
description: A Magda Authentication Plugin for Australian Access Federation (AAF) Rapid Connect.
version: "1.0.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-auth-aaf"
sources: ["https://github.com/magda-io/magda-auth-aaf"]
dependencies:
  - name: magda-common
    version: "1.2.0"
    repository: "https://charts.magda.io"

